language: python
puthon: 3.8
script:
  - cd Rep6.2
  - pytest
  - cd ..

deploy:
  provider: releases
  prerelease: true
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  on:
    repo: PolinaK1/Rep6.2
    branch: dev
    tags: false
